version: '3.1'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    container_name: apirest_scode
    environment:
      MYSQL_ROOT_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_DATABASE: ${SPRING_DATASOURCE_DB}
    ports:
      - "3307"
    volumes:
      - /Documents/vol:/var/lib/mysql